typeof(revenues)
revenues
rev14 <- read.csv("revenue2014.csv", stringsAsFactors = FALSE, na.strings = " ")
rev15 <- read.csv("revenue2015.csv", stringsAsFactors = FALSE, na.strings = " ")
sapply(list(rev14, rev15), dim)
str(rev14)
colnames(rev14) <- c("date", "payer", "purpose", "amount", "pay.mode", "remark")
str(rev14)
rev14 <- rev14[-1, ]
str(rev14)
rev14 <- rev14[, -(7:8)]
str(rev14)
as.numeric(rev14$amount)
stringr::str_trim(rev14$amount)
rev14$amount <- stringr::str_trim(rev14$amount)
str(rev14)
as.numeric(rev14$amount)
str(rev14)
stringr::str_replace(rev14$amount, pattern = ",", replacement = "")
stringr::str_replace(rev14$amount, pattern = "+,", replacement = "")
stringr::str_replace(rev14$amount, pattern = ",+", replacement = "")
gsub(pattern = ",+", replacement = "", rev14$amount)
rev14$amount <- gsub(pattern = ",+", replacement = "", rev14$amount)
str(rev14)
rev14$amount <- as.numeric(rev14$amount)
str(rev14)
tail(rev14$date)
as.Date(rev14$date)
